import type { RiskBand } from '../types/risk';

export type ConditionType =
  | 'GENERAL'
  | 'SEPSIS_SUSPECT'
  | 'MATERNAL_PREECLAMPSIA'
  | 'MATERNAL_HEMORRHAGE'
  | 'NEONATAL_DISTRESS';

export interface ActionCard {
  id: string;
  riskBand: RiskBand;
  condition: ConditionType;
  title: string;
  whatsHappening: string;
  whatToDo: string[];
  whenToEscalate: string;
  doNotDo: string[];
  timeframe: string;
  colorCode: 'GREEN' | 'YELLOW' | 'ORANGE' | 'RED';
  source: string;
}

export const ACTION_CARDS: ActionCard[] = [
  // ── GENERAL ──────────────────────────────────────────────────────────────
  {
    id: 'GEN-LOW',
    riskBand: 'LOW',
    condition: 'GENERAL',
    title: 'Routine Monitoring',
    whatsHappening: 'Vital signs are within acceptable limits. Continue standard care.',
    whatToDo: [
      'Continue regular observations per ward protocol.',
      'Document findings and re-assess in 12 hours.',
      'Encourage oral hydration and rest.',
    ],
    whenToEscalate: 'Escalate immediately if any single parameter worsens to score 3.',
    doNotDo: ['Do not discharge without confirming stable trend over 2+ readings.'],
    timeframe: 'Reassess within 12 hours',
    colorCode: 'GREEN',
    source: 'Royal College of Physicians — NEWS2 2017',
  },
  {
    id: 'GEN-MED',
    riskBand: 'MEDIUM',
    condition: 'GENERAL',
    title: 'Urgent Ward Review',
    whatsHappening: 'One or more vital signs are abnormal. Urgent clinical review is needed.',
    whatToDo: [
      'Notify the ward nurse immediately.',
      'Increase monitoring frequency to at least every 1 hour.',
      'Establish IV access and draw blood for FBC, U&E, lactate.',
      'Administer supplemental oxygen if SpO2 < 94%.',
    ],
    whenToEscalate: 'Escalate to emergency team if score rises to 7 or any parameter reaches 3.',
    doNotDo: ['Do not leave patient unmonitored.', 'Do not delay escalation.'],
    timeframe: 'Reassess within 1 hour',
    colorCode: 'YELLOW',
    source: 'Royal College of Physicians — NEWS2 2017',
  },
  {
    id: 'GEN-HIGH',
    riskBand: 'HIGH',
    condition: 'GENERAL',
    title: 'Emergency Clinical Assessment',
    whatsHappening: 'Significant physiological deterioration detected. Emergency response required.',
    whatToDo: [
      'Call emergency clinical team NOW.',
      'Commence continuous monitoring (ECG, pulse oximetry, BP).',
      'Establish IV access × 2, take bloods (FBC, U&E, LFT, CRP, lactate, blood cultures × 2).',
      'Administer high-flow oxygen via non-rebreather mask if hypoxic.',
      'Prepare resuscitation trolley.',
    ],
    whenToEscalate: 'Escalate to ICU if score reaches 9 or consciousness changes.',
    doNotDo: ['Do not leave patient alone.', 'Do not give oral fluids if consciousness impaired.'],
    timeframe: 'Reassess within 30 minutes',
    colorCode: 'ORANGE',
    source: 'Royal College of Physicians — NEWS2 2017',
  },
  {
    id: 'GEN-CRIT',
    riskBand: 'CRITICAL',
    condition: 'GENERAL',
    title: 'Immediate Emergency Response',
    whatsHappening: 'Life-threatening deterioration. Immediate emergency intervention required.',
    whatToDo: [
      'Activate emergency response team (Code Blue / equivalent) IMMEDIATELY.',
      'Commence ABCDE assessment.',
      'High-flow O2 15 L/min via non-rebreather mask.',
      'IV fluid bolus 500 mL 0.9% NaCl over 15 minutes if hypotensive.',
      'Prepare for possible ICU transfer or urgent procedure.',
    ],
    whenToEscalate: 'ICU transfer if no improvement within 15 minutes.',
    doNotDo: ['Do not delay calling for help.', 'Do not attempt oral medications.'],
    timeframe: 'Immediate — continuous monitoring',
    colorCode: 'RED',
    source: 'Royal College of Physicians — NEWS2 2017',
  },
  // ── SEPSIS_SUSPECT ───────────────────────────────────────────────────────
  {
    id: 'SEP-LOW',
    riskBand: 'LOW',
    condition: 'SEPSIS_SUSPECT',
    title: 'Possible Infection — Monitor',
    whatsHappening: 'Mild abnormalities may indicate early infection. Close monitoring is required.',
    whatToDo: [
      'Check temperature every 2 hours.',
      'Collect blood cultures × 2 if not already done.',
      'Check urine dipstick and culture.',
      'Measure serum lactate if available.',
    ],
    whenToEscalate: 'Escalate if lactate > 2 mmol/L or any parameter worsens.',
    doNotDo: ['Do not start antibiotics without senior review unless clearly indicated.'],
    timeframe: 'Reassess within 2 hours',
    colorCode: 'GREEN',
    source: 'Surviving Sepsis Campaign 2021; WHO Sepsis Guidelines',
  },
  {
    id: 'SEP-MED',
    riskBand: 'MEDIUM',
    condition: 'SEPSIS_SUSPECT',
    title: 'Sepsis Screening — Urgent',
    whatsHappening: 'Clinical picture consistent with possible sepsis. Urgent screening required.',
    whatToDo: [
      'Start sepsis screening tool.',
      'Establish IV access, take bloods: FBC, U&E, LFT, CRP, lactate, blood cultures × 2.',
      'Give IV fluid challenge 500 mL 0.9% NaCl if systolic BP < 100.',
      'Notify senior clinician within 30 minutes.',
    ],
    whenToEscalate: 'Escalate if lactate > 4 mmol/L or systolic BP < 90 despite fluids.',
    doNotDo: ['Do not delay blood cultures before antibiotics if patient is clearly septic.'],
    timeframe: 'Reassess within 30 minutes',
    colorCode: 'YELLOW',
    source: 'Surviving Sepsis Campaign 2021',
  },
  {
    id: 'SEP-HIGH',
    riskBand: 'HIGH',
    condition: 'SEPSIS_SUSPECT',
    title: 'Sepsis Six — Act Now',
    whatsHappening: 'Probable sepsis with significant physiological compromise. Time-critical intervention required.',
    whatToDo: [
      'Give high-flow oxygen to achieve SpO2 ≥ 94%.',
      'Take blood cultures × 2 BEFORE antibiotics.',
      'Give IV antibiotics within 1 hour of recognition (per local protocol).',
      'Give IV fluid challenge 30 mL/kg 0.9% NaCl over 3 hours.',
      'Measure urine output — insert urinary catheter.',
      'Measure serum lactate — repeat in 2 hours.',
    ],
    whenToEscalate: 'Escalate to ICU if lactate > 4 or no response to fluids in 1 hour.',
    doNotDo: ['Do not delay antibiotics.', 'Do not give oral fluids.'],
    timeframe: 'Reassess within 30 minutes',
    colorCode: 'ORANGE',
    source: 'Surviving Sepsis Campaign 2021; UK Sepsis Trust',
  },
  {
    id: 'SEP-CRIT',
    riskBand: 'CRITICAL',
    condition: 'SEPSIS_SUSPECT',
    title: 'Septic Shock — Emergency',
    whatsHappening: 'Septic shock: life-threatening organ dysfunction from infection. Mortality risk is high.',
    whatToDo: [
      'Activate emergency team IMMEDIATELY.',
      'High-flow O2 15 L/min non-rebreather.',
      'IV antibiotics within 1 hour (broad spectrum).',
      'IV fluid resuscitation 30 mL/kg rapidly.',
      'Start vasopressors (noradrenaline) if MAP < 65 mmHg despite fluids.',
      'ICU referral NOW.',
    ],
    whenToEscalate: 'ICU transfer required. Do not delay.',
    doNotDo: ['Do not wait for lab results before starting antibiotics.', 'Do not give hypotonic fluids.'],
    timeframe: 'Immediate — continuous monitoring',
    colorCode: 'RED',
    source: 'Surviving Sepsis Campaign 2021',
  },
  // ── MATERNAL_PREECLAMPSIA ────────────────────────────────────────────────
  {
    id: 'MPE-LOW',
    riskBand: 'LOW',
    condition: 'MATERNAL_PREECLAMPSIA',
    title: 'Elevated BP — Maternal Monitoring',
    whatsHappening: 'Blood pressure is slightly elevated in a pregnant patient. Close monitoring required.',
    whatToDo: [
      'Measure BP in both arms, use the higher reading.',
      'Test urine for proteinuria (dipstick).',
      'Check for symptoms: headache, visual disturbance, epigastric pain.',
      'Notify midwife or obstetrician.',
    ],
    whenToEscalate: 'Escalate if BP ≥ 160/110 or symptoms develop.',
    doNotDo: ['Do not dismiss elevated BP as "white coat" in pregnancy.'],
    timeframe: 'Reassess within 30 minutes',
    colorCode: 'GREEN',
    source: 'NICE Guideline NG133 — Hypertension in Pregnancy 2019',
  },
  {
    id: 'MPE-MED',
    riskBand: 'MEDIUM',
    condition: 'MATERNAL_PREECLAMPSIA',
    title: 'Possible Pre-eclampsia',
    whatsHappening: 'BP pattern and symptoms suggest possible pre-eclampsia. Urgent obstetric review required.',
    whatToDo: [
      'Notify obstetrician immediately.',
      'Measure urine protein (PCR or 24h urine if time allows).',
      'Check FBC, LFT, U&E, uric acid.',
      'Assess fetal wellbeing (CTG if ≥ 26 weeks).',
      'Consider oral labetalol or nifedipine if BP ≥ 150/100.',
    ],
    whenToEscalate: 'Escalate if BP exceeds 160/110, symptoms develop, or fetal compromise.',
    doNotDo: ['Do not give ACE inhibitors in pregnancy.', 'Do not delay senior review.'],
    timeframe: 'Reassess within 30 minutes',
    colorCode: 'YELLOW',
    source: 'NICE NG133; WHO Recommendations on Prevention of Pre-eclampsia 2011',
  },
  {
    id: 'MPE-HIGH',
    riskBand: 'HIGH',
    condition: 'MATERNAL_PREECLAMPSIA',
    title: 'Severe Pre-eclampsia',
    whatsHappening: 'Severe pre-eclampsia. Risk of maternal seizure (eclampsia) and fetal compromise is high.',
    whatToDo: [
      'Call senior obstetrician URGENTLY.',
      'Give magnesium sulfate 4g IV over 5 minutes (loading dose) to prevent seizures.',
      'Antihypertensives IV: labetalol 20 mg IV bolus or hydralazine 5 mg IV.',
      'Urinary catheter — hourly urine output monitoring.',
      'Fluid restrict to 80 mL/hour (risk of pulmonary oedema).',
      'Prepare for possible urgent delivery.',
    ],
    whenToEscalate: 'Escalate immediately if seizure occurs or fetal decelerations.',
    doNotDo: ['Do not over-hydrate.', 'Do not delay magnesium sulfate.'],
    timeframe: 'Reassess every 15 minutes',
    colorCode: 'ORANGE',
    source: 'WHO Recommendations for Prevention and Treatment of Pre-eclampsia 2011',
  },
  {
    id: 'MPE-CRIT',
    riskBand: 'CRITICAL',
    condition: 'MATERNAL_PREECLAMPSIA',
    title: 'Eclampsia / Hypertensive Crisis',
    whatsHappening: 'Hypertensive emergency or eclamptic seizure. Maternal and fetal life at immediate risk.',
    whatToDo: [
      'Activate obstetric emergency team IMMEDIATELY.',
      'If seizing: airway management, place in left lateral position.',
      'Magnesium sulfate 4g IV over 5 minutes, then 1g/hour infusion.',
      'Antihypertensives to keep systolic BP < 160 mmHg.',
      'Emergency caesarean section if fetus viable and condition not controlled.',
      'ICU or HDU admission.',
    ],
    whenToEscalate: 'Immediate escalation — this IS the emergency.',
    doNotDo: ['Do not leave the patient alone.', 'Do not attempt oral medications during seizure.'],
    timeframe: 'Immediate — continuous monitoring',
    colorCode: 'RED',
    source: 'WHO Recommendations for Prevention and Treatment of Pre-eclampsia 2011',
  },
  // ── MATERNAL_HEMORRHAGE ──────────────────────────────────────────────────
  {
    id: 'MHE-LOW',
    riskBand: 'LOW',
    condition: 'MATERNAL_HEMORRHAGE',
    title: 'Postpartum Bleeding — Monitor',
    whatsHappening: 'Mild postpartum bleeding. Close monitoring is essential to catch deterioration early.',
    whatToDo: [
      'Quantify blood loss (weigh pads).',
      'Monitor vital signs every 15 minutes.',
      'Ensure uterus is well contracted (fundal massage if not).',
      'Bladder: check for urinary retention.',
    ],
    whenToEscalate: 'Escalate if blood loss > 500 mL or vital signs change.',
    doNotDo: ['Do not underestimate visual blood loss — weigh it.'],
    timeframe: 'Reassess every 15 minutes',
    colorCode: 'GREEN',
    source: 'WHO Guidelines for the Management of Postpartum Haemorrhage 2012',
  },
  {
    id: 'MHE-MED',
    riskBand: 'MEDIUM',
    condition: 'MATERNAL_HEMORRHAGE',
    title: 'Postpartum Haemorrhage',
    whatsHappening: 'Significant postpartum haemorrhage (> 500 mL or haemodynamic change).',
    whatToDo: [
      'Call senior midwife / obstetrician NOW.',
      'Establish 2 large-bore IV lines.',
      'Give oxytocin 10 units IV (first-line uterotonic).',
      'Bimanual uterine compression if uterus atonic.',
      'Send FBC, clotting, crossmatch (4 units pRBC).',
    ],
    whenToEscalate: 'Escalate to major PPH protocol if blood loss > 1000 mL.',
    doNotDo: ['Do not delay oxytocin.', 'Do not give ergometrine if hypertensive.'],
    timeframe: 'Reassess every 5 minutes',
    colorCode: 'YELLOW',
    source: 'WHO Guidelines for the Management of Postpartum Haemorrhage 2012',
  },
  {
    id: 'MHE-HIGH',
    riskBand: 'HIGH',
    condition: 'MATERNAL_HEMORRHAGE',
    title: 'Major PPH — Emergency Protocol',
    whatsHappening: 'Major postpartum haemorrhage (> 1000 mL). Haemodynamic compromise.',
    whatToDo: [
      'Activate major PPH protocol.',
      'High-flow O2 15 L/min.',
      'Rapid IV crystalloid then blood products (1:1:1 pRBC:FFP:platelets).',
      'Second-line uterotonics: misoprostol 800 mcg sublingual + carboprost 250 mcg IM.',
      'Activate cell saver if available.',
      'Consider tranexamic acid 1g IV within 3 hours of birth.',
    ],
    whenToEscalate: 'Escalate to theatre for surgical control if bleeding continues > 30 min.',
    doNotDo: ['Do not withhold blood products.', 'Do not give excessive crystalloid (> 1.5L).'],
    timeframe: 'Reassess every 5 minutes',
    colorCode: 'ORANGE',
    source: 'WHO Guidelines for the Management of Postpartum Haemorrhage 2012',
  },
  {
    id: 'MHE-CRIT',
    riskBand: 'CRITICAL',
    condition: 'MATERNAL_HEMORRHAGE',
    title: 'Haemorrhagic Shock — Activate All Teams',
    whatsHappening: 'Life-threatening haemorrhagic shock. Immediate surgical and anaesthetic intervention required.',
    whatToDo: [
      'Activate emergency obstetric theatre NOW.',
      'Massive transfusion protocol: pRBC, FFP, platelets, cryoprecipitate.',
      'Aortic compression if exsanguinating.',
      'Bakri balloon or B-Lynch suture if uterine atony.',
      'Hysterectomy if all other measures fail.',
      'ICU admission post-operatively.',
    ],
    whenToEscalate: 'Immediate — all available personnel to the bedside.',
    doNotDo: ['Do not delay theatre.', 'Do not attempt oral or IM medications.'],
    timeframe: 'Immediate — continuous monitoring',
    colorCode: 'RED',
    source: 'RCOG Green-top Guideline No. 52 — PPH 2016',
  },
  // ── NEONATAL_DISTRESS ────────────────────────────────────────────────────
  {
    id: 'NEO-LOW',
    riskBand: 'LOW',
    condition: 'NEONATAL_DISTRESS',
    title: 'Neonate — Routine Assessment',
    whatsHappening: 'Newborn vital signs are within normal range. Continue standard neonatal care.',
    whatToDo: [
      'Ensure warmth (skin-to-skin or radiant warmer).',
      'Assess feeding: breastfeeding within 1 hour if possible.',
      'Monitor colour, tone, and breathing.',
      'Vitamin K prophylaxis as per protocol.',
    ],
    whenToEscalate: 'Escalate if respiratory rate > 60, grunting, or colour changes.',
    doNotDo: ['Do not bathe neonate until temperature stable > 36.5°C.'],
    timeframe: 'Reassess within 4 hours',
    colorCode: 'GREEN',
    source: 'WHO Pocket Book of Hospital Care for Children 2013',
  },
  {
    id: 'NEO-MED',
    riskBand: 'MEDIUM',
    condition: 'NEONATAL_DISTRESS',
    title: 'Neonatal Concern — Urgent Review',
    whatsHappening: 'Neonate showing signs of possible distress. Urgent paediatric review required.',
    whatToDo: [
      'Notify paediatrician or neonatal nurse immediately.',
      'Apply pulse oximetry (right hand, pre-ductal).',
      'Keep neonate warm and with mother if safe.',
      'Assess blood glucose — treat hypoglycaemia (< 2.6 mmol/L) with buccal glucose gel.',
    ],
    whenToEscalate: 'Escalate to NICU if SpO2 < 90% persists or breathing worsens.',
    doNotDo: ['Do not leave neonate unattended.'],
    timeframe: 'Reassess within 30 minutes',
    colorCode: 'YELLOW',
    source: 'WHO Pocket Book of Hospital Care for Children 2013',
  },
  {
    id: 'NEO-HIGH',
    riskBand: 'HIGH',
    condition: 'NEONATAL_DISTRESS',
    title: 'Neonatal Respiratory Distress',
    whatsHappening: 'Neonate in respiratory distress. Urgent neonatal team assessment required.',
    whatToDo: [
      'Call neonatal emergency team.',
      'Provide supplemental oxygen — target SpO2 90–95% (term) or 90–94% (preterm).',
      'Continuous positive airway pressure (CPAP) if available.',
      'Check blood glucose and temperature.',
      'IV access if oral route not safe.',
    ],
    whenToEscalate: 'Escalate to NICU and consider intubation if no improvement in 30 minutes.',
    doNotDo: ['Do not give oral feeds during respiratory distress.'],
    timeframe: 'Reassess every 15 minutes',
    colorCode: 'ORANGE',
    source: 'WHO Essential Newborn Care; NRP 8th Edition',
  },
  {
    id: 'NEO-CRIT',
    riskBand: 'CRITICAL',
    condition: 'NEONATAL_DISTRESS',
    title: 'Neonatal Resuscitation Required',
    whatsHappening: 'Neonate in cardiorespiratory arrest or severe collapse. Immediate resuscitation.',
    whatToDo: [
      'Start NRP (Neonatal Resuscitation Program) IMMEDIATELY.',
      'Dry, warm, stimulate.',
      'Open airway — 30 seconds of effective ventilation.',
      'If HR < 60: chest compressions 3:1 with ventilation.',
      'IV/IO adrenaline 10 mcg/kg if HR < 60 after 60 seconds of CPR.',
      'Activate neonatal emergency team.',
    ],
    whenToEscalate: 'NICU transfer immediately after stabilisation.',
    doNotDo: ['Do not delay resuscitation.', 'Do not stop within first 10 minutes without senior decision.'],
    timeframe: 'Immediate — continuous monitoring',
    colorCode: 'RED',
    source: 'NRP 8th Edition; WHO Essential Newborn Care Guidelines',
  },
];

export function getActionCard(
  condition: ConditionType,
  band: RiskBand
): ActionCard | undefined {
  return ACTION_CARDS.find((c) => c.condition === condition && c.riskBand === band);
}
